
CREATE TABLE `country_code_config`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `country_code` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `country_code3` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `country_code_num` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `currency` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '货币代码',
  `symbol` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '货币符号',
  `support_flag` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '业务支持标记:0不支持，1支持',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_name`(`country_name`) USING BTREE,
  INDEX `idx_code2`(`country_code`) USING BTREE,
  INDEX `idx_code3`(`country_code3`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 250 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

CREATE TABLE `proj_energy_analysis`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `proj_id` bigint(30) NOT NULL COMMENT '项目id',
  `annual_p_r` decimal(20, 6) NULL DEFAULT NULL COMMENT '年度PR/%',
  `ele_from_pv` decimal(20, 6) NULL DEFAULT NULL COMMENT '能量流入-光伏发电/kWh',
  `ele_from_power_grid` decimal(20, 6) NULL DEFAULT NULL COMMENT '能量流入-电网发电/kWh',
  `ele_to_household` decimal(20, 6) NULL DEFAULT NULL COMMENT '家庭用电/kWh',
  `ele_to_power_grid` decimal(20, 6) NULL DEFAULT NULL COMMENT '电网卖电/kWh',
  `ele_excess` decimal(20, 6) NULL DEFAULT NULL COMMENT '富余电量/kWh',
  `is_del` tinyint(3) UNSIGNED NULL DEFAULT 0 COMMENT '是否删除，0：未删除，1：已删除',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建人uid',
  `update_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '更新人uid',
  `decreased_ele_purchased_amount` decimal(20, 6) NULL DEFAULT NULL COMMENT '减少的买电电量/度',
  `decreased_ele_purchased_cost` decimal(20, 6) NULL DEFAULT NULL COMMENT '减少的买点费用/元',
  `increased_ele_sold_amount` decimal(20, 6) NULL DEFAULT NULL COMMENT '增加的卖电电量/度',
  `increased_ele_sold_return` decimal(20, 6) NULL DEFAULT NULL COMMENT '增加的卖电收益/元',
  `self_use_rate` decimal(10, 6) NULL DEFAULT NULL COMMENT '年度自发自用率占比',
  `ele_excess_rate` decimal(10, 6) NULL DEFAULT NULL COMMENT '上网电量占总电量占比',
  `actual_power` decimal(20, 6) NULL DEFAULT NULL COMMENT '年度发电量/kW',
  `generation_hours` decimal(20, 6) NULL DEFAULT NULL COMMENT '年度小时数',
  `avg_use_ele_price` decimal(20, 6) NULL DEFAULT NULL COMMENT '平均电价',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_proj`(`proj_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1905547826741346306 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '首年能量分析' ROW_FORMAT = Dynamic;

CREATE TABLE `proj_energy_analysis_month`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `proj_id` bigint(20) NULL DEFAULT NULL COMMENT '项目编号',
  `month` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '月份',
  `ele_self_use` decimal(16, 4) NULL DEFAULT NULL COMMENT '自发自用电量',
  `ele_sell` decimal(16, 4) NULL DEFAULT NULL COMMENT '余电上网电量',
  `ele_exess` decimal(16, 4) NULL DEFAULT NULL COMMENT '富余电量',
  `bill_before` decimal(20, 4) NULL DEFAULT NULL COMMENT '安装光伏前月度账单',
  `bill_after` decimal(20, 4) NULL DEFAULT NULL COMMENT '安装光伏后月度账单',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_proj_id`(`proj_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 0 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '月度账单对比' ROW_FORMAT = DYNAMIC;

CREATE TABLE `proj_generation_simulation_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `proj_id` bigint(20) NOT NULL COMMENT '项目编码',
  `roof_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '屋顶编码',
  `inverter_id` bigint(20) NOT NULL COMMENT '逆变器编号',
  `volumetric_ratio` decimal(10, 2) NULL DEFAULT NULL COMMENT '容配比',
  `string_capacity` decimal(12, 2) NULL DEFAULT NULL COMMENT '当前逆变器连接组件容量',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_proj_id`(`proj_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1896851349197623942 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `proj_info`  (
  `id` bigint(30) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `proj_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目名称',
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目地址',
  `grid_param` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '电网参数字典项',
  `weather_station` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '气象站编号',
  `export_limit` decimal(20, 8) NULL DEFAULT NULL COMMENT '并网功率限制（千瓦）',
  `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '备注',
  `currency` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'USD' COMMENT '货币缩写，默认USD',
  `proj_type` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '1' COMMENT '项目类型：户用1，工商业2',
  `design_type` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '标准设计1；简易设计2',
  `country_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '国家编码',
  `customer_appellation` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '客户称呼：先生/女士/Mrs./Mr.',
  `customer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '客户名称',
  `installed_power` decimal(20, 8) NULL DEFAULT NULL COMMENT '装机功率(单位kw)',
  `status` tinyint(4) NULL DEFAULT NULL COMMENT '项目状态：未开始0，进行中1，已完成2',
  `is_del` tinyint(3) UNSIGNED NULL DEFAULT 0 COMMENT '是否删除，0：未删除，1：已删除',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建人uid',
  `update_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '更新人uid',
  `is_feed` int(2) NULL DEFAULT 1 COMMENT '是否馈电:0否，1是',
  `lon` double NULL DEFAULT NULL COMMENT '项目地址经度',
  `lat` double NULL DEFAULT NULL COMMENT '项目地址纬度',
  `pic_resolution` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '图片分辨率',
  `customer_email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '客户邮箱',
  `customer_phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '客户手机号',
  `zoom` decimal(20, 8) NULL DEFAULT NULL COMMENT '定位到指定的级别',
  `pic_height` int(11) NULL DEFAULT NULL COMMENT '图片高度',
  `pic_width` int(11) NULL DEFAULT NULL COMMENT '图片宽度',
  `evaluation_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评估时间',
  `pv_unit_capacity` decimal(20, 8) NULL DEFAULT NULL COMMENT '光伏系统容量(单位kW)',
  `es_unit_capacity` decimal(20, 8) NULL DEFAULT NULL COMMENT '储能系统容量(单位kW)',
  `evaluation_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '评估人',
  `customized_picture` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '自定义的地图底图',
  `area_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '区域编码sys_global_area_info',
  `string_invert_num` int(20) NULL DEFAULT NULL COMMENT '组串逆变器数量',
  `mppt_str_num` int(20) NULL DEFAULT NULL COMMENT '组串串联数众数',
  `grid_param_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '电网参数名称',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_page_query`(`design_type`, `status`, `create_time`, `is_del`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1905546506215063554 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '项目基本信息' ROW_FORMAT = Dynamic;

CREATE TABLE `proj_report_overview`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `proj_id` bigint(30) NOT NULL COMMENT '项目id',
  `annual_income` decimal(20, 4) NULL DEFAULT NULL COMMENT '首年度收入/元',
  `total_income` decimal(20, 4) NULL DEFAULT NULL COMMENT '25年总收入',
  `investment_cost` decimal(20, 4) NULL DEFAULT NULL COMMENT '投资费用/元',
  `roi` decimal(16, 4) NULL DEFAULT NULL COMMENT '投资收益率/%',
  `annual_power_generation` decimal(12, 4) NULL DEFAULT NULL COMMENT '年度发电/度',
  `system_capacity` decimal(12, 4) NULL DEFAULT NULL COMMENT '系统容量/千瓦',
  `payback_period` decimal(12, 4) NULL DEFAULT NULL COMMENT '回本周期/年',
  `annual_return_rate` decimal(16, 4) NULL DEFAULT NULL COMMENT '年化收益率irr/%',
  `is_del` tinyint(3) UNSIGNED NULL DEFAULT 0 COMMENT '是否删除，0：未删除，1：已删除',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建人uid',
  `update_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '更新人uid',
  `income_list` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '25年收入列表',
  `annual_subsidy` decimal(20, 4) NULL DEFAULT NULL COMMENT '首年补贴',
  `total_subsidy` decimal(20, 4) NULL DEFAULT NULL COMMENT '25年累计补贴',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_proj`(`proj_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 0 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '报告总览' ROW_FORMAT = Dynamic;

CREATE TABLE `sys_global_area_info`  (
  `gid` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `country` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '国家编码',
  `level` tinyint(2) NULL DEFAULT NULL COMMENT '区域层级',
  `long_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '全称',
  `short_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '简称',
  `p_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '父级编码',
  `is_del` tinyint(3) UNSIGNED NULL DEFAULT 0 COMMENT '是否删除，0：未删除，1：已删除',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建人uid',
  `update_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '更新人uid',
  PRIMARY KEY (`gid`) USING BTREE,
  UNIQUE INDEX `uni_country_shortname`(`country`, `short_name`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '全球区域配置（一级区域，部分国家）' ROW_FORMAT = Dynamic;

CREATE TABLE `user_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户ID',
  `user_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户名',
  `first_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '名',
  `last_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '姓',
  `user_role` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户角色：1-管理员，2-销售人员，3-安装商，4-经销商',
  `user_call` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户称呼',
  `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '邮箱',
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '密码',
  `phone_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '手机号',
  `country` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '1' COMMENT '国家/地区',
  `city` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '市/县',
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '地址',
  `company_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '公司名称',
  `super_distributor_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '上级经销商代码',
  `source` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '来源',
  `is_del` tinyint(2) UNSIGNED NULL DEFAULT 0 COMMENT '是否删除，0：未删除，1：已删除',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新增时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建人uid',
  `update_uid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '更新人uid',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '用户详细信息' ROW_FORMAT = Dynamic;